### PR TITLE
Added sample code for node.js

### PR DESCRIPTION
**Pull request by hemanth**
fix for #45

### CODE REVIEW

**Comment by rnicholus** [comment]
It looks like your example only handles the preflight request.  There is an [existing express example](https://github.com/mhausenblas/enable-cors.org/blob/gh-pages/server_expressjs.html), but it does not handle preflights.  Perhaps you could contribute a modification to the express example that incorporates preflight handling?

**Comment by monsur** [comment]
Thank you for pulling this together. However, as this code stands at the moment, it is incomplete in that it only handles preflights and not the actual request. Plus it hard-codes many details (such as headers and credentials) that users may want to customize. I think a more robust and flexible implementation would be helpful. Thanks!

**Comment by hemanth** [comment]
@rnicholus I wanted a raw node example here so did that.

@monsur I agree! Will work on it :)

**Comment by monsur** [comment]
Thanks. Please resubmit the pull request when this is ready.

**Comment by hemanth** [comment]
@monsur Yikes, had missed this, will send a new PR soon. Thank you.

**Pull request closed without merging**
